version: '{build}'
shallow_clone: true

platform: x64

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

matrix:
  fast_finish: false

install:

before_build:
  - git --version
  - set PATH=C:\Python38-x64;%PATH%
  - python -V
  - python -m site --user-base
  - dir C:\Users\appveyor\AppData\Roaming\Python

build_script:
  - cmake -version
