sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: gcc

install:
  - if [ $TRAVIS_OS_NAME == linux ];then sudo apt-get install -yqq mono-complete; fi
  - if [ $TRAVIS_OS_NAME == osx ];then brew update; fi
  - if [ $TRAVIS_OS_NAME == osx ];then brew cask install java; fi
  - if [ $TRAVIS_OS_NAME == osx ];then brew install mono; fi

script:
  - env
  - make --version
  - cmake --version

  - if [ $TRAVIS_OS_NAME == linux ];then which java | xargs ls -l | xargs ls -l; fi
  - if [ $TRAVIS_OS_NAME == linux ];then ls -l /usr/lib/jvm/*; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then which java | xargs ls -l; fi

  - which dotnet && (which dotnet | xargs ls -l )
  - which csharp && (which csharp | xargs ls -l )

