language: cpp

git:
  depth: false
  quiet: true
  submodules: false

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: gcc

    - os: osx
      compiler: gcc

    - os: windows

before_script:
  - if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == osx ]]; then env; fi
  - if [[ $TRAVIS_OS_NAME == windows ]]; then set; fi
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == osx ]]; then
     make --version || true
     cmake --version | grep version || true
    fi
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
     cmake --version | grep version || true
     cmake -G "" || true
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == osx ]]; then
      set -x
      git --version | grep version || true
      git lfs | grep "git-lfs" || true
      hg --version | grep version || true
      svn --version | grep "\<version\>" || true
      cat /proc/cpuinfo | grep "flags" || true
      ls -R /usr/lib/jvm || true
    fi
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
      git --version | grep version || true
      git lfs | grep "git-lfs" || true
      hg --version | grep version || true
      svn --version | grep "\<version\>" || true
    fi
  - |
    if [ $TRAVIS_OS_NAME == osx ];then
      brew --version || true
      sysctl -a | grep machdep.cpu.features | cut -f2 -d: | tr . _ || true
    fi
