language: cpp

git:
  depth: false
  quiet: true
  submodules: false

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: gcc

    - os: osx
      compiler: gcc

    - os: windows

before_script:
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == linux ]]; then
     env
     make --version
     cmake --version
    fi
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
     set
     make --version
     cmake --version
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == linux ]]; then
      git --version || true
      git-lfs --version || true
      hg --version || true
      svn --version || true
    fi
  - |
    if [ $TRAVIS_OS_NAME == osx ];then
      brew --version || true
    fi
