language: cpp

git:
  depth: false
  quiet: true
  submodules: false

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: gcc

    - os: osx
      compiler: gcc

    - os: windows

before_script:
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == osx ]]; then
     env
    fi
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == osx ]]; then
     make --version || true
     cmake --version | grep version || true
    fi
  - |
    if [[ $TRAVIS_OS_NAME == windows ]]; then
     set
     cmake --version
     make --version
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME == linux ]] || [[ $TRAVIS_OS_NAME == osx ]]; then
      git --version | grep version || true
      git lfs || true
      hg --version | grep version || true
      svn --version | grep "\<version\>" || true
    fi
  - |
    if [ $TRAVIS_OS_NAME == osx ];then
      brew --version || true
    fi
