sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: gcc

install:
  - if [ $TRAVIS_OS_NAME == linux ];then sudo apt-get install -yqq mono-complete; fi
  - if [ $TRAVIS_OS_NAME == osx ];then brew update; fi
  # get readlinks on osx
  - if [ $TRAVIS_OS_NAME == osx ];then brew install coreutils; fi
  - if [ $TRAVIS_OS_NAME == osx ];then brew cask install java; fi
  - if [ $TRAVIS_OS_NAME == osx ];then brew install mono; fi

script:
  - env
  - make --version
  - cmake --version

  - if [ $TRAVIS_OS_NAME == linux ];then which java && which java | xargs readlink -f; fi
  - if [ $TRAVIS_OS_NAME == linux ];then ls -l /usr/lib/jvm/*; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then which java && wich java | xargs readlink -f; fi

  - which mono && which mono | xargs readlink -f
  - which mcs && which mcs | xargs readlink -f
  - which csharp && which csharp | xargs readlink -f
