sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: gcc

install:
  - sudo apt-get install -yqq mono-complete

script:
  - env
  - make --version
  - cmake --version
  - which java | xargs ls -l | xargs ls -l || true
  - ls -l /usr/lib/jvm/*
  - which dotnet && (which dotnet | xargs ls -l ) || true
  - which csharp && (which csharp | xargs ls -l ) || true

