sudo: required
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: gcc

install:
  - echo "install done"

script:
  - env
  - make --version
  - cmake --version
  - which java | xargs ls -l
  - ls /usr/lib/jvm/*/bin
  - which dotnet && (which dotnet | xargs ls -l )

