name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: env
      run: env
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    # Base
    - name: Git
      run: git --version
    - name: Make
      run: make --version
    - name: CMake
      run: cmake -version
    - name: GCC
      run: gcc --version
    - name: G++
      run: g++ --version
    - name: Clang
      run: clang --version
    - name: CPU Flags
      run: cat /proc/cpuinfo | grep "flags"
    # Java
    - name: Java
      run: mvn --version
    # .Net
    - name: .NET
      run: dotnet --info
    # Python
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - name: Python3
      run: |
        python3 --version
        python3 -m site --user-base
    - name: Pip
      run: |
        pip --version

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: env
      run: "Get-ChildItem Env:"
    # Base
    - name: Git
      run: git --version
    - name: Make
      run: make --version
    - name: CMake
      run: cmake -version
    # .Net
    - name: .NET
      run: dotnet --info
    # Java
    - name: Java
      run: mvn --version
    # Python
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - name: Python3
      run: |
        python3 --version
        python3 -m site --user-base
    - name: Pip
      run: |
        pip --version

  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: env
      run: env
    # Base
    - name: Git
      run: git --version
    - name: Make
      run: make --version
    - name: Install brew Make
      run: |
        brew install make
        echo "/usr/local/opt/make/libexec/gnubin" >> $GITHUB_PATH
    - name: Make
      run: make --version
    - name: CMake
      run: cmake -version
    - name: GCC
      run: gcc --version
    - name: G++
      run: g++ --version
    - name: Clang
      run: clang --version
    - name: CPU Flags
      run: "sysctl -a | grep machdep.cpu.features | cut -f2 -d: | tr . _"
    # .Net
    - name: .NET
      run: dotnet --info
    # Java
    - name: Java
      run: mvn --version
    # Python
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - name: Pip
      run: |
        pip --version
    - name: Python3
      run: |
        python3 --version
        python3 -m site --user-base
    - name: Pip3
      run: |
        pip3 --version
