name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Git
      run: git --version
    - name: CMake
      run: cmake -version
    - name: Make
      run: make --version
    - name: GCC
      run: gcc --version
    - name: G++
      run: g++ --version
    - name: Clang
      run: clang --version
    - name: CPU Flags
      run: cat /proc/cpuinfo | grep "flags"
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - name: Python 3
      run: |
        python3 --version
        python3 -m site --user-base
    - name: Java
      run: mvn --version
    - name: .NET
      run: dotnet --info

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: "Get-ChildItem Env:"
    - name: Add PATH
      run: echo "$((Get-Item ~).FullName)/appdata/roaming/python/python37/Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Git
      run: git --version
    - name: CMake
      run: cmake -version
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - name: Java
      run: mvn --version
    - name: .NET
      run: dotnet --info

  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Add PATH
      run: echo "$HOME/Library/Python/3.9/bin" >> $GITHUB_PATH
    - name: Git
      run: git --version
    - name: CMake
      run: cmake -version
    - name: Make
      run: make --version
    - name: GCC
      run: gcc --version
    - name: G++
      run: g++ --version
    - name: Clang
      run: clang --version
    - name: CPU Flags
      run: "sysctl -a | grep machdep.cpu.features | cut -f2 -d: | tr . _"
    - name: Python
      run: |
        python --version
        python -m site --user-base
    - name: Python 3
      run: |
        python3 --version
        python3 -m site --user-base
    - name: Java
      run: mvn --version
    - name: .NET
      run: dotnet --info

