name: Docker

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info
    - name: Pull image
      run: docker pull mcr.microsoft.com/windows:2009
    - name: Build image
      run: docker build -f win.Dockerfile .

  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info
