name: docker

on: [push, pull_request, workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker
      run: docker info
    - name: platform
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

