# ref: https://github.com/actions/runner-images
name: Docker Support

on: [push, pull_request, workflow_dispatch]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info
    - name: platforms
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx ls

  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info

  Windows:
    strategy:
      matrix:
        runner: [
          windows-latest,
          windows-2022,
          windows-2019,
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    - name: docker version
      run: docker version
    - name: docker info
      run: docker info
    - name: Pull image
      run: docker pull mcr.microsoft.com/windows:ltsc2019
    - name: Build image
      run: docker build -f win.Dockerfile .
