# ref: https://github.com/actions/runner-images
# ref: https://github.com/actions/partner-runner-images
name: Docker Support

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  linux:
    strategy:
      matrix:
        runner: [
          ubuntu-latest,
          ubuntu-24.04, # ubuntu-latest
          ubuntu-22.04,
          ubuntu-24.04-arm, # partner runner image in Beta
          ubuntu-22.04-arm, # partner runner image in Beta
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: Linux(${{matrix.runner}})
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: Supported platforms
        run: docker buildx inspect || true

  macos:
    strategy:
      matrix:
        runner: [
          macos-latest, # M1
          macos-13, # amd64
          #macos-12, # deprecated
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: MacOS(${{matrix.runner}})
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: docker version
        run: docker version || true
      - name: docker info
        run: docker info || true
      - name: Supported platforms
        run: docker buildx inspect || true

  windows:
    strategy:
      matrix:
        runner: [
          windows-latest,
          windows-2025,
          windows-2022, # windows-latest
          #windows-2019, # deprecated
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: Windows(${{matrix.runner}})
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: Supported platforms
        shell: bash
        run: docker buildx inspect || true
      #- name: Pull image
      #  run: docker pull mcr.microsoft.com/windows:ltsc2019
      #- name: Build image
      #  run: docker build -f win.Dockerfile .
