name: Test Matrix

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [
          [A1, A2],
          [B1, B2],
          [C1, C2]
        ]
        bar: [
          {v1: "1.1", v2: "1.2"},
          {v1: "2.1", v2: "2.2"}
        ]
      fail-fast: false
    env:
      FIRST: ${{matrix.foo[0]}}
      SECOND: ${{matrix.foo[1]}}
    steps:
      - uses: actions/checkout@v5
      - name: Print
        run: |
          echo $FIRST $SECOND
          echo "v1: ${{matrix.bar.v1}}, v2: ${{matrix.bar.v2}}""

  merge:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v5
