name: Test

on: [push, pull_request]

jobs:
  tuple:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [ [A, A1], [B, B1] ]
      fail-fast: false
    env:
      FIRST: ${{ matrix.foo[0] }}
      SECOND: ${{ matrix.foo[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Print
      run: echo $FIRST $SECOND
