name: Vagrant Support

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: vagrant
      run: vagrant --version || true
    - name: virtualbox
      run: virtualbox --help || true

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: vagrant
      run: vagrant --version || true
    - name: virtualbox
      run: virtualbox --help || true

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: vagrant
      run: vagrant --version || true
    - name: virtualbox
      run: virtualbox --help || true

