# ref: https://github.com/actions/runner-images
name: Vagrant Support

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    strategy:
      matrix:
        runner: [
          ubuntu-latest,
          ubuntu-24.04, # ubuntu-latest
          ubuntu-22.04,
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: Linux(${{matrix.runner}})
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: vagrant
        run: vagrant --version || true
      - name: virtualbox
        run: virtualbox --help || true

  macos:
    strategy:
      matrix:
        runner: [
          macos-latest, # M1
          macos-13, # amd64
          #macos-12, # deprecated
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: MacOS(${{matrix.runner}})
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: vagrant
        run: vagrant --version || true
      - name: virtualbox
        run: virtualbox --help || true

  windows:
    strategy:
      matrix:
        runner: [
          windows-latest,
          windows-2025,
          windows-2022, # windows-latest
          #windows-2019, # deprecated
        ]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: Windows(${{matrix.runner}})
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: vagrant
        run: vagrant --version || true
      - name: virtualbox
        run: virtualbox --help || true
